django/tiantian/goods_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name="index"),

]

django/tiantian/tiantian/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('tiantian_project.urls',namespace="tiantian")),
    url(r'^', include('goods_app.urls',namespace="goods")),
]

django/tiantian/tiantian_project/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$',views.register,name="register"),
    url(r'^register_handle/$',views.register_handle,name="register_handle"),
    url(r'^check_username/$',views.check_username,name="check_username"),
    url(r'^login/$',views.login,name="login"),
    url(r'^login_handle/$',views.login_handle,name="login_handle"),
    url(r'^user_center_info/$',views.user_center_info,name="user_center_info"),
    url(r'^user_center_info_register/$',views.user_center_info_register,name="user_center_info_register"),
    url(r'^user_center_info_register_handle$',views.user_center_info_register_handle,name
    	="user_center_info_register_handle"),
    url(r'^user_center_order$',views.user_center_order,name="user_center_order"),
]

django/tiantian/goods_app/models.py
from django.db import models

# Create your models here.

django/tiantian/tiantian_project/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
	user_name = models.CharField(max_length=20)
	user_passwd = models.CharField(max_length=40)
	user_mail = models.CharField(max_length=30)

	def __str__(self):
		return self.user_name



class User_address_info(models.Model):
	address = models.CharField(max_length=100)
	tel_num = models.CharField(max_length=12)
	user = models.ForeignKey(UserInfo)
	
	def __str__(self):
		return str(self.user)

django/tiantian/goods_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	name = request.session.get('user',None)
	if name != None:
		context = {'user':name,'status':1}
	else:
		context = {'user':"",'status':0}
	return render(request,'goods/index.html',context)

django/tiantian/tiantian_project/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from .models import *
from hashlib import sha1
import re

# Create your views here.
def register(request):
	return render(request,'user/register.html')

def register_handle(request):
	#获取用户提交的信息
	name = request.POST['user_name']
	pwd = request.POST['pwd']
	cpwd = request.POST['cpwd']
	email = request.POST['email']

	#判断密码是否相同
	if pwd != cpwd:
		return redirect(reverse('tiantian:register'))

	#判断邮箱是否正确
	if re.match(r'^[0-9a-zA-Z_]{0,19}@[0-9a-zA-Z]{1,13}\.[com,cn,net]{1,3}$',email) == None:
		return redirect(reverse('tiantian:register'))

	# 密码加密：
	s1 = sha1()
	s1.update(pwd.encode("utf-8"))
	passwd = s1.hexdigest()
	# 加密 end

	user = UserInfo()
	user.user_name = name
	user.user_passwd = passwd
	user.user_mail = email
	user.save()

	return redirect(reverse('tiantian:login'))

	# return render(request,)

def check_username(request):
	print('test')
	name = request.GET['name']
	print(name)
	count = UserInfo.objects.filter(user_name=name).count() #这里使用的是count的方式来计算过滤出来的值有多少个
	print(count)                     #能使用count的原因是过滤出来的是一个数组
	if count:
		print('1')
		return JsonResponse({'status':1})
	else:
		print('0')
		return JsonResponse({'status':0})

def login(request):
	return render(request,'user/login.html')

def login_handle(request):
	name = request.POST['username']
	pwd = request.POST['pwd']
	#获取密码的加密格式字符串
	s1 = sha1()
	s1.update(pwd.encode("utf-8"))
	passwd = s1.hexdigest()	
	# 加密 end

	#比较用户名
	count = UserInfo.objects.filter(user_name=name).count()
	if count == 0:
		return redirect(reverse('tiantian:login'))
	else:
		user = UserInfo.objects.get(user_name=name)
		if user.user_passwd != passwd:
			status = 0
			return redirect(reverse('tiantian:login'))
		else:
			status = 1
			request.session['user']=name
			request.session.set_expiry(300)
			return redirect(reverse('goods:index'))


def user_center_info(request):
	name = request.session.get('user',None)

	if name == None:
		return redirect(reverse('tiantian:login'))

	user = UserInfo.objects.get(user_name=name)
	addr = user.user_address_info_set.all()
	if addr.count() == 0:
		return redirect(reverse('tiantian:user_center_info_register'))
	address = []
	for i in addr:
		address.append(i)
	context = {'name':name,'address':address}
	return render(request,'user/user_center_info.html',context)

def user_center_info_register(request):
	name = request.session.get('user',None)
	if name == None:
		return redirect(reverse('tiantian:login'))
	else:
		user = UserInfo.objects.get(user_name=name)
		addr = user.user_address_info_set.all()
		if addr.count() == 0:
			status=0
		else:
			status=1

		address = []
		for i in addr:
			address.append(i)
		context = {'name':name,'address':address,'status':status}
		print(context)
	return render(request,'user/user_center_site.html',context)

def user_center_info_register_handle(request):
	tel_num = request.POST['tel_num']
	address = request.POST['address']

	if len(tel_num)<5 or len(address)<5:
		return redirect(reverse('tiantian:user_center_info_register'))

	username = request.session.get('user',None)
	if username == None:
		return redirect(reverse('tiantian:register'))
	user = UserInfo.objects.get(user_name=username)
	user.user_address_info_set.create(address=address,tel_num=tel_num)
	return redirect(reverse('tiantian:user_center_info'))


def user_center_order(request):
	return render(request,'user/user_center_order.html')

django/tiantian/templates/goods/base_head_foot.html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	{% block head %} {% endblock %}
</head>
<body>

	{% block body %} {% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>


{% block foot_js %} {% endblock %}

</body>
</html>

django/tiantian/templates/tiantian/login.html
{% extends 'tiantian/base_head_foot.html' %}

{% block head %}
	<title>天天生鲜-登录</title>
	{% load static from staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'tiantian/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'tiantian/css/main.css' %}">
{% endblock %}

{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'tiantian:index' %}" class="login_logo"><img src="{% static 'tiantian/images/logo02.png' %} "></a>	
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'tiantian:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'tiantian:login_handle' %}" method="POST">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

django/tiantian/templates/tiantian/register.html

{% extends "tiantian/base_foot.html" %}

{% block head %}
	{% load static from staticfiles %}
	<script type="text/javascript" src="{% static 'tiantian/js/register.js' %}"></script>
	<script type="text/javascript">
		
		$(function(){

			$('#user_name').change(function(){
				$.ajax({   //这里是使用ajax的方式进行数据传输交换，因为ajax既可以将js中的数据传输到django中
                    url: '{% url 'tiantian:check_username' %}',//又可以从jango中取出数据
                    data: {name:$(this).val()},
                    // contentType: 'application/json',
                    type: "GET", //这里采用的是GET的方式进行数据请求
                    traditional: true,    // 需要传递列表、字典时加上这句
                    success: function(result) {  //这里便是从django中取出数据
                        if(result.status==0){
                        	console.log('0');
                        }
                        else{
                        	console.log(result.status);
                        }
                    },

                });


			});

		})


	</script>
{% endblock %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'tiantian/images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'tiantian:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'tiantian:register_handle' %}" method="POST">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

{% endblock %}

django/tiantian/templates/user/base_foot.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-注册</title>
	{% load static from staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'tiantian/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'tiantian/css/main.css' %} ">
	<script type="text/javascript" src="{% static 'tiantian/js/jquery-1.12.4.min.js' %} "></script>

	{% block head%} {% endblock %}

</head>
<body>

{% block body %}


{% endblock %}



	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

django/tiantian/templates/user/base_head_foot.html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	{% block head %} {% endblock %}
</head>
<body>

	{% block body %} {% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>


{% block foot_js %} {% endblock %}

</body>
</html>

django/tiantian/templates/user/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-购物车</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods012.jpg"></li>
		<li class="col03">奇异果<br><em>25.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">25.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">25.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods003.jpg"></li>
		<li class="col03">大兴大棚草莓<br><em>16.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">16.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">16.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="place_order.html">去结算</a></li>
	</ul>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

django/tiantian/templates/user/login.html
{% extends 'user/base_head_foot.html' %}

{% block head %}
	<title>天天生鲜-登录</title>
	{% load static from staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'tiantian/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'tiantian/css/main.css' %}">
{% endblock %}

{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'tiantian/images/logo02.png' %} "></a>	
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'tiantian:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'tiantian:login_handle' %}" method="POST">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

django/tiantian/templates/user/register.html

{% extends "user/base_foot.html" %}

{% block head %}
	{% load static from staticfiles %}
	<script type="text/javascript" src="{% static 'tiantian/js/register.js' %}"></script>
	<script type="text/javascript">
		
		$(function(){

			$('#user_name').change(function(){
				$.ajax({   //这里是使用ajax的方式进行数据传输交换，因为ajax既可以将js中的数据传输到django中
                    url: '{% url 'tiantian:check_username' %}',//又可以从jango中取出数据
                    data: {name:$(this).val()},
                    // contentType: 'application/json',
                    type: "GET", //这里采用的是GET的方式进行数据请求
                    traditional: true,    // 需要传递列表、字典时加上这句
                    success: function(result) {  //这里便是从django中取出数据
                        if(result.status==0){
                        	console.log('0');
                        }
                        else{
                        	console.log(result.status);
                        }
                    },

                });


			});

		})


	</script>
{% endblock %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'tiantian/images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'tiantian:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'tiantian:register_handle' %}" method="POST">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

{% endblock %}

django/tiantian/templates/user/user_center_site.html
{% extends 'user/base_head_foot.html' %}

{% block head %}
	<title>天天生鲜-用户中心</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'tiantian/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'tiantian/css/main.css' %}">
{% endblock%}

{% block body %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'tiantian:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'tiantian:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'tiantian:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'tiantian/images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'tiantian:user_center_info' %}">· 个人信息</a></li>
				<li><a href="user_center_order.html">· 全部订单</a></li>
				<li><a href="{% url 'tiantian:user_center_info_register' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
							{% for addr in address %}
							<dd>{{addr.address}} {{ addr.tel_num }}</dd>
							{% endfor %}
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{% url 'tiantian:user_center_info_register_handle' %}" method="POST">
						{% csrf_token %}
						<div class="form_group">
							<label>{{name}}: </label>
						</div>
						{% if status %}

						<div class="form_group">
							<label>创建新的地址： </label>
						</div>

						{% else %}
						<div class="form_group">
							<label>请创建： </label>
						</div>

						{% endif %}
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="tel_num">
						</div>
						
						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock%}