django/jason_test/booktest/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name="index"),
	url(r'^upload/',views.upload,name="upload"),
	url(r'^pages/',views.pages,name="pages"),
	url(r'^book_index/',views.book_index, name="book_index"),
	url(r'^ajax_get/',views.ajax_get,name="ajax_get"),
	url(r'^get_bookinfo/',views.get_bookinfo,name="get_bookinfo"),
	url(r'^editor/',views.editor,name="editor"),
	url(r'^editor_handle',views.editor_handle,name="editor_handle"),
]

django/jason_test/jason_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('booktest.urls',namespace="booktest")),
    url(r'^tinymce',include('tinymce.urls')),
]

# here can rewrite the 404function , if want to use this function ,you need to set debug to False in settings.py
# handler404 = 'booktest.views.my_custom_page_not_found_view' 

django/jason_test/booktest/models.py
from django.db import models
from tinymce.models import HTMLField

# Create your models here.

class BookInfo(models.Model):
	btitle = models.CharField(max_length=20)
	bpub_date = models.DateTimeField()
	bread = models.IntegerField(default=0)
	bcommet = models.IntegerField(default=0)
	isDelete = models.BooleanField(default=False)
	bcontent = HTMLField()




	def __str__(self):
		return self.btitle


class HeroInfo(models.Model):
	hname = models.CharField(max_length=20)
	hgender = models.BooleanField(default=1)
	hBook = models.ForeignKey('BookInfo')
	hcontent = models.CharField(max_length=100)
	isDelete = models.BooleanField(default=False)
	

	def __str__(self):
		return self.hname

django/jason_test/booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from .models import *
from django.core.paginator import Paginator
import json
# Create your views here.

def index(request):
    return render(request,'booktest/index.html')
    # return HttpResponse('ok')


def upload(request):

    if request.method == 'POST':
        picture = request.FILES['picture']
        fname = '%s/cars/%s'%(settings.MEDIA_ROOT, picture.name)
        # return HttpResponse(settings.MEDIA_ROOT)
        with open(fname,'wb') as pic:
            for c in picture.chunks():
                pic.write(c)
        return HttpResponse('ok')
    else:
        return HttpResponse('error')
def my_custom_page_not_found_view(request):
    return HttpResponse('fail 404 fail')

def pages(request,id):
    if id == '':
        id = '1'
    list = HeroInfo.objects.all()
    paginator = Paginator(list,5)
    page = paginator.page(int(id))
    context = {'page':page}

    return render(request,'booktest/pages.html',context)

def book_index(request):
    return render(request,'booktest/book_index.html')

def ajax_get(request):
    # print('hello')
    book_list = BookInfo.objects.all()
    # print(book_list)
    # return JsonResponse({'data':book_list}) #这样返回数据会报错
    l = []
    for list in book_list:
        l.append((list.id,list.btitle)) #这里必须要将获得的book_list进行遍历，取出元素放在一个数组中才行，否则会报错
    return JsonResponse({'data':l}) #具体为什么这样的原因还有待解析

def get_bookinfo(request):
    print('test')
    id = request.GET['id'] #这里使用的是ajax的方式进行数据的传递
    print(id)
    list=HeroInfo.objects.filter(hBook_id=id)#这里的filter返回的是一个查询集，并不是一个对象，而是一个对象集合
    print(list)
    hero_list = []
    for i in list:
        hero_list.append((i.id,i.hname))
    return JsonResponse({'data':hero_list})

#富文本编辑器
def editor(request):
    data = BookInfo.objects.all()
    list = []
    for l in data:
        list.append([l.id,l.btitle])
    print(list)
    context = {'data':list}
    return render(request,'booktest/editor.html',context)

def editor_handle(request):
    html = request.POST['hcontent'] #此处获取的是大文本提交的内容
    id = request.POST['select'] #此处获取的是要提交的id号
    print('id:',id)
    print(html)
    book = BookInfo.objects.get(pk=id) #注意filter方法返回的是一个查询集合，是一个集合，get返回的是一个对象
    print(book.btitle)
    book.bcontent = html
    book.save()
    return HttpResponse('ok')

django/jason_test/templates/booktest/book_index.html
<!DOCTYPE html>
<html>
<head>
	<title>book_index</title>
	<!-- 如下是通过静态文件的方式加载了jquery，同理其他形式的js、CSS等的加载方式一样 -->
	{% load static from staticfiles %}
<script type="text/javascript" src="{% static 'booktest/js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript">
	
	$(function(){  //这是jquery的操作方式

		// alert($); //这是判断jquery是否正常工作的方式
		book = $('#book')
		$.get('{% url 'booktest:ajax_get' %}', function(dic) {
			console.log(dic);
			$.each(dic.data,function(index,item){

				book.append('<option value="'+item[0]+'">'+item[1]+'</option>');
				// console.log()
			});

		});

		$('#book').change(function(){
			$('#hero').empty().append('<option value="">请选择英雄</option>');

			$.ajax({   //这里是使用ajax的方式进行数据传输交换，因为ajax既可以将js中的数据传输到django中
    				url: '{% url 'booktest:get_bookinfo' %}',//又可以从jango中取出数据
    				data: {id:$(this).val()},
    				// contentType: 'application/json',
    				type: "GET", //这里采用的是GET的方式进行数据请求
    				traditional: true,    // 需要传递列表、字典时加上这句
    				success: function(result) {  //这里便是从django中取出数据
    					$.each(result.data,function(index,item){
							$('#hero').append('<option value="'+item[0]+'">'+item[1]+'</option>');
						});
    				}
				});
			});

	});


</script>

</head>

<body>

<form>
	<select id="book">
		<option value="">请选择书</option>
	</select>

	<select id="hero">
		<option value="">请选择英雄</option>
	</select>

</form>


</body>
</html>

django/jason_test/templates/booktest/editor.html
<!DOCTYPE html>
<html>
<head>
    <title>editro</title>
    {% load static from staticfiles %}
    <script type="text/javascript" src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
    <script type="text/javascript">
        tinyMCE.init({
            'mode':'textareas',
            'theme':'advanced',
            'width':400,
            'height':100
        });
    </script>
</head>
<body>
<form method="post" action="{% url 'booktest:editor_handle' %}">
	{% csrf_token %}
    <select name="select">
    	{% for index,item in data %}
    	<option value="{{index}}">{{item}}</option>
    	{% endfor %}
    </select>
    <br>
    <textarea name='hcontent'>哈哈，这是啥呀</textarea>
    <br>
    <input type="submit" value="提交">
</form>
</body>
</html>

django/jason_test/templates/booktest/index.html
<!DOCTYPE html>
<html>
<head>
	<title>static file</title>
</head>
<body>
<!-- {% load static from staticfiles %}
<img src="{% static "booktest/img/1.png" %} " alt="1.png" /> -->

<form method="POST" action="{% url 'booktest:upload' %}" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="file" name="picture"> <br/>
	<input type="submit" name=""/>

</form>

<!-- <h1>test</h1> -->

</body>
</html>

django/jason_test/templates/booktest/pages.html
<!DOCTYPE html>
<html>
<head>
	<title>pages</title>
</head>
<body>

<ul>
	{% for index in page %}

	<li> {{ index.hname }}</li>

	{% endfor %}

</ul>

<ul>
	{% for i in page.paginator.page_range %}
	<a href="{% url 'booktest:pages' i %}">{{i}}</a>
	{% endfor %}
</ul>

<!-- <h1>test</h1> -->
</body>
</html>